SET NAMES UTF8;
DROP DATABASE IF EXISTS `fruit`;
CREATE DATABASE `fruit` CHARSET=UTF8;
USE `fruit`;


-- 管理员表
CREATE TABLE `admin`(
`aid` INT(11) PRIMARY KEY AUTO_INCREMENT,
`aname` VARCHAR(32) DEFAULT NULL,
`apwd` VARCHAR(32) DEFAULT NULL
);

INSERT INTO admin VALUES(NULL,'admin','admin');

-- 员工表

CREATE TABLE `emp`(
  `eid` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `ename` VARCHAR(32) DEFAULT NULL,
  `epwd` VARCHAR(32) DEFAULT NULL,
  `esex` INT(11) DEFAULT NULL,
  `eage` INT(11) DEFAULT NULL,
  `ephone` VARCHAR(16) DEFAULT NULL,
  `work_time` VARCHAR(16)DEFAULT NULL
)

